const CATALOG_ENTRIES = [
  ['peticao_inicial', 'Petição Inicial Cível', 'peticao_inicial', 2],
  ['contestacao', 'Contestação', 'contestacao', 2],
  ['replica', 'Réplica à Contestação', 'replica', 2],
  ['reconvencao', 'Reconvenção', 'reconvencao', 2],
  ['impugnacao', 'Impugnação', 'impugnacao', 2],
  ['agravo_instrumento', 'Agravo de Instrumento', 'agravo_instrumento', 2],
  ['agravo_interno', 'Agravo Interno', 'agravo_interno', 2],
  ['recurso', 'Apelação Cível', 'recurso_apelacao', 2],
  ['embargos_declaracao', 'Embargos de Declaração', 'embargos_declaracao', 1],
  ['acao_cobranca', 'Ação de Cobrança', 'peticao_inicial', 2, 'DE COBRANÇA'],
  ['acao_monitoria', 'Ação Monitória', 'peticao_inicial', 2, 'MONITÓRIA'],
  ['acao_danos_morais', 'Danos Morais', 'peticao_inicial', 2, 'INDENIZATÓRIA POR DANOS MORAIS'],
  ['acao_danos_materiais', 'Danos Materiais', 'peticao_inicial', 2, 'INDENIZATÓRIA POR DANOS MATERIAIS'],
  ['acao_obrigacao_fazer', 'Obrigação de Fazer', 'peticao_inicial', 2, 'DE OBRIGAÇÃO DE FAZER'],
  ['tutela_antecipada', 'Tutela de Urgência', 'tutela_antecipada', 2],
  ['mandado_seguranca', 'Mandado de Segurança', 'mandado_seguranca', 2],
  ['cumprimento_sentenca', 'Cumprimento de Sentença', 'cumprimento_sentenca', 2],
  ['execucao_titulo_extrajudicial', 'Execução de Título Extrajudicial', 'execucao_titulo', 2],
  ['impugnacao_cumprimento', 'Impugnação ao Cumprimento', 'impugnacao_cumprimento', 2],
  ['reclamacao_trabalhista', 'Reclamação Trabalhista', 'reclamacao_trabalhista', 2],
  ['contestacao_trabalhista', 'Contestação Trabalhista', 'contestacao_trabalhista', 2],
  ['replica_trabalhista', 'Réplica Trabalhista', 'replica_trabalhista', 2],
  ['calculos_trabalhistas', 'Cálculos Trabalhistas', 'calculos_trabalhistas', 2],
  ['recurso_ordinario', 'Recurso Ordinário', 'recurso_ordinario', 2],
  ['agravo_peticao', 'Agravo de Petição', 'agravo_peticao', 2],
  ['embargos_execucao', 'Embargos à Execução', 'embargos_execucao', 2],
  ['pedido_horas_extras', 'Pedido de Horas Extras', 'reclamacao_trabalhista', 2, 'HORAS EXTRAS'],
  ['rescisao_indireta', 'Rescisão Indireta', 'reclamacao_trabalhista', 2, 'RESCISÃO INDIRETA'],
  ['acidente_trabalho', 'Acidente de Trabalho', 'reclamacao_trabalhista', 2, 'ACIDENTE DE TRABALHO'],
  ['carta_preposicao', 'Carta de Preposição', 'carta_preposicao', 1],
  ['aposentadoria_idade', 'Aposentadoria por Idade', 'previdenciario_inicial', 2, 'APOSENTADORIA POR IDADE'],
  ['aposentadoria_invalidez', 'Aposentadoria por Invalidez', 'previdenciario_inicial', 2, 'APOSENTADORIA POR INVALIDEZ'],
  ['auxilio_doenca', 'Auxílio-Doença', 'previdenciario_inicial', 2, 'AUXÍLIO-DOENÇA'],
  ['bpc_loas', 'BPC/LOAS', 'previdenciario_inicial', 2, 'BPC/LOAS'],
  ['pensao_morte', 'Pensão por Morte', 'previdenciario_inicial', 2, 'PENSÃO POR MORTE'],
  ['revisao_beneficio', 'Revisão de Benefício', 'previdenciario_inicial', 2, 'REVISÃO DE BENEFÍCIO'],
  ['recurso_administrativo_inss', 'Recurso Administrativo INSS', 'recurso_administrativo', 2],
  ['mandado_seguranca_previdenciario', 'MS Previdenciário', 'mandado_seguranca', 2],
  ['divorcio_consensual', 'Divórcio Consensual', 'familia_peticao', 2, 'DIVÓRCIO CONSENSUAL'],
  ['divorcio_litigioso', 'Divórcio Litigioso', 'familia_peticao', 2, 'DIVÓRCIO LITIGIOSO'],
  ['guarda_compartilhada', 'Guarda Compartilhada', 'familia_peticao', 2, 'GUARDA COMPARTILHADA'],
  ['regulamentacao_visitas', 'Regulamentação de Visitas', 'familia_peticao', 2, 'REGULAMENTAÇÃO DE VISITAS'],
  ['pensao_alimenticia', 'Pensão Alimentícia', 'familia_peticao', 2, 'ALIMENTOS'],
  ['revisional_alimentos', 'Revisional de Alimentos', 'familia_peticao', 2, 'REVISIONAL DE ALIMENTOS'],
  ['exoneracao_alimentos', 'Exoneração de Alimentos', 'familia_peticao', 2, 'EXONERAÇÃO DE ALIMENTOS'],
  ['inventario', 'Inventário', 'familia_peticao', 2, 'INVENTÁRIO'],
  ['arrolamento', 'Arrolamento', 'familia_peticao', 2, 'ARROLAMENTO'],
  ['uniao_estavel', 'União Estável', 'familia_peticao', 2, 'UNIÃO ESTÁVEL'],
  ['dissolucao_uniao_estavel', 'Dissolução de União Estável', 'familia_peticao', 2, 'DISSOLUÇÃO DE UNIÃO ESTÁVEL'],
  ['interdicao', 'Interdição', 'familia_peticao', 2, 'INTERDIÇÃO'],
  ['curatela', 'Curatela', 'familia_peticao', 2, 'CURATELA'],
  ['acao_contra_banco', 'Ação contra Banco', 'consumidor_inicial', 2, 'CONTRA BANCO'],
  ['acao_contra_telefonia', 'Ação contra Telefonia', 'consumidor_inicial', 2, 'CONTRA TELEFONIA'],
  ['acao_contra_companhia_aerea', 'Ação contra Companhia Aérea', 'consumidor_inicial', 2, 'CONTRA COMPANHIA AÉREA'],
  ['negativacao_indevida', 'Negativação Indevida', 'consumidor_inicial', 2, 'NEGATIVAÇÃO INDEVIDA'],
  ['cobranca_indevida', 'Cobrança Indevida', 'consumidor_inicial', 2, 'COBRANÇA INDEVIDA'],
  ['vicio_produto', 'Vício do Produto', 'consumidor_inicial', 2, 'VÍCIO DO PRODUTO'],
  ['vicio_servico', 'Vício do Serviço', 'consumidor_inicial', 2, 'VÍCIO DO SERVIÇO'],
  ['danos_morais_consumidor', 'Danos Morais ao Consumidor', 'consumidor_inicial', 2, 'DANOS MORAIS — CDC'],
  ['recurso_inominado', 'Recurso Inominado (JEC)', 'recurso_inominado', 2],
  ['contrato_social', 'Contrato Social', 'contrato_social', 2],
  ['alteracao_contratual', 'Alteração Contratual', 'alteracao_contratual', 2],
  ['distrato_social', 'Distrato Social', 'distrato_social', 2],
  ['recuperacao_judicial', 'Recuperação Judicial', 'recuperacao_judicial', 2],
  ['cobranca_empresarial', 'Cobrança Empresarial', 'peticao_inicial', 2, 'COBRANÇA EMPRESARIAL'],
  ['execucao_empresarial', 'Execução Empresarial', 'execucao_titulo', 2],
  ['usucapiao', 'Usucapião', 'imobiliario_inicial', 2, 'USUCAPIÃO'],
  ['despejo', 'Despejo', 'imobiliario_inicial', 2, 'DESPEJO'],
  ['cobranca_aluguel', 'Cobrança de Aluguel', 'imobiliario_inicial', 2, 'COBRANÇA DE ALUGUEL'],
  ['acao_possessoria', 'Ação Possessória', 'imobiliario_inicial', 2, 'POSSESSÓRIA'],
  ['reintegracao_posse', 'Reintegração de Posse', 'imobiliario_inicial', 2, 'REINTEGRAÇÃO DE POSSE'],
  ['imissao_posse', 'Imissão na Posse', 'imobiliario_inicial', 2, 'IMISSÃO NA POSSE'],
  ['adjudicacao_compulsoria', 'Adjudicação Compulsória', 'imobiliario_inicial', 2, 'ADJUDICAÇÃO COMPULSÓRIA'],
  ['habeas_corpus', 'Habeas Corpus', 'habeas_corpus', 2],
  ['liberacao_provisoria', 'Liberdade Provisória', 'liberacao_provisoria', 2],
  ['revogacao_prisao_preventiva', 'Revogação de Prisão Preventiva', 'revogacao_prisao', 2],
  ['resposta_acusacao', 'Resposta à Acusação', 'resposta_acusacao', 2],
  ['memorial', 'Memoriais / Alegações Finais', 'memorial', 2],
  ['recurso_sentido_estrito', 'Recurso em Sentido Estrito', 'recurso_sentido_estrito', 2],
  ['apelacao_criminal', 'Apelação Criminal', 'apelacao_criminal', 2],
  ['procuracao', 'Procuração Ad Judicia', 'procuracao', 1],
  ['procuracao_poderes_especiais', 'Procuração c/ Poderes Especiais', 'procuracao', 1],
  ['substabelecimento', 'Substabelecimento', 'substabelecimento', 1],
  ['notificacao_extrajudicial', 'Notificação Extrajudicial', 'notificacao_extrajudicial', 2],
  ['parecer_juridico', 'Parecer Jurídico', 'parecer_juridico', 2],
  ['declaracao', 'Declaração', 'declaracao', 1],
  ['contrato', 'Contrato de Prestação de Serviços', 'contrato', 2],
  ['contrato_honorarios', 'Contrato de Honorários', 'contrato_honorarios', 2],
  ['acordo_extrajudicial', 'Termo de Acordo', 'acordo_extrajudicial', 2],
  ['confissao_divida', 'Confissão de Dívida', 'confissao_divida', 2],
  ['distrato', 'Distrato Contratual', 'distrato', 2],
  ['requerimento_administrativo', 'Requerimento Administrativo', 'requerimento_administrativo', 1],
  ['recurso_administrativo', 'Recurso Administrativo', 'recurso_administrativo', 2],
];

const DOCUMENT_CATALOG = Object.fromEntries(
  CATALOG_ENTRIES.map(([id, nome, structure, custo_tokens, defaultTipoAcao]) => [
    id,
    { id, nome, structure, custo_tokens, defaultTipoAcao: defaultTipoAcao || null },
  ])
);

function getCatalogEntry(id) {
  return DOCUMENT_CATALOG[id] || null;
}

function listCatalog() {
  return Object.values(DOCUMENT_CATALOG).map(({ id, nome, custo_tokens }) => ({
    id,
    nome,
    custoTokens: custo_tokens,
  }));
}

function getDocumentTypeLabels() {
  return Object.fromEntries(Object.values(DOCUMENT_CATALOG).map((e) => [e.id, e.nome]));
}

module.exports = {
  DOCUMENT_CATALOG,
  getCatalogEntry,
  listCatalog,
  getDocumentTypeLabels,
};
