# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: my gpt-5
    provider: openai
    model: gpt-5
    apiKey:eJwtzL1OwzAUQOF3ubOHlPxU9gYCwdAOCBBispzr68bEja3rJMWq+u5IVdYjfecKBpFy/owjTaCg2zet3LmOsEa0jZOISNRKt+9l3faVM66WtnMgIHFcvSXe6HU76XlbnYaoy/vXUD3Y9pfNbnh8zW+lVIen9eP7uD6Prul+quYFBNyJnksiUNCTYWIQkDHeg7FnP6m09MGjHqkIJmNV5JNgSlEsmVjR2fggLpFHF+IFBNBf8kxZmxnUtIRwu/0DEAxQ6A==
  - uses: ollama/qwen2.5-coder-7b
  - uses: anthropic/claude-4-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
